// wordData.ts - 500+ Transport Words
export interface WordEntry {
    term: string;
    definition: string;
    points: number;
}

export const WORDS: WordEntry[] = [
    // === SINGLE WORD TERMS (1 point each) - 200+ words ===
    { term: "engine", definition: "A machine that converts fuel into mechanical energy to power a vehicle", points: 1 },
    { term: "transmission", definition: "The mechanism that transmits power from the engine to the wheels", points: 1 },
    { term: "brake", definition: "A device for slowing or stopping a moving vehicle", points: 1 },
    { term: "accelerator", definition: "The pedal that controls the speed of a vehicle", points: 1 },
    { term: "clutch", definition: "A pedal that engages and disengages the engine from the transmission", points: 1 },
    { term: "radiator", definition: "A device that cools the engine by circulating coolant", points: 1 },
    { term: "alternator", definition: "A generator that charges the battery while the engine runs", points: 1 },
    { term: "carburetor", definition: "A device that mixes air and fuel for internal combustion engines", points: 1 },
    { term: "suspension", definition: "The system of springs and shock absorbers that absorbs road shocks", points: 1 },
    { term: "dashboard", definition: "The panel in front of the driver containing instruments and controls", points: 1 },
    { term: "headlight", definition: "A powerful light at the front of a vehicle for illumination", points: 1 },
    { term: "windshield", definition: "The front window of a vehicle", points: 1 },
    { term: "ignition", definition: "The system that starts the engine", points: 1 },
    { term: "turbocharger", definition: "A device that increases engine power by forcing more air into cylinders", points: 1 },
    { term: "differential", definition: "A gear system that allows wheels to rotate at different speeds", points: 1 },
    { term: "hatchback", definition: "A car with a door at the back that opens upward", points: 1 },
    { term: "sedan", definition: "A common passenger car with a separate trunk for luggage", points: 1 },
    { term: "convertible", definition: "A passenger car that can be driven with or without a roof", points: 1 },
    { term: "coupe", definition: "A two-door car with a fixed roof and a sloping rear", points: 1 },
    { term: "minivan", definition: "A passenger vehicle designed for transporting families", points: 1 },
    { term: "pickup", definition: "A light truck with an open body and low sides", points: 1 },
    { term: "suv", definition: "Sport Utility Vehicle designed for off-road use", points: 1 },
    { term: "offroader", definition: "A vehicle specifically designed for driving on unpaved surfaces", points: 1 },
    { term: "chassis", definition: "The load-bearing framework that supports the body of a vehicle", points: 1 },
    { term: "driveshaft", definition: "A component for transmitting torque and rotation in a vehicle", points: 1 },
    { term: "fuelinjector", definition: "A nozzle that sprays fuel into the engine's cylinders", points: 1 },
    { term: "sparkplug", definition: "A device for delivering electric current to the combustion chamber", points: 1 },
    { term: "brakepad", definition: "The component that applies pressure to the brake rotor", points: 1 },
    { term: "turnsignal", definition: "A flashing light used to show that a vehicle is about to turn", points: 1 },
    { term: "catalyticconverter", definition: "A device that reduces toxic gases in exhaust", points: 1 },
    { term: "muffler", definition: "A device for reducing the noise emitted by an engine", points: 1 },
    { term: "pistons", definition: "Components that move up and down in cylinders to create power", points: 1 },
    { term: "cylinders", definition: "The chambers where fuel is burned to create power", points: 1 },
    { term: "valves", definition: "Components that control the flow of air and fuel in an engine", points: 1 },
    { term: "crankshaft", definition: "A shaft that converts reciprocating motion to rotational motion", points: 1 },
    { term: "camshaft", definition: "A shaft with cams that opens and closes engine valves", points: 1 },
    { term: "flywheel", definition: "A rotating mechanical device used to store rotational energy", points: 1 },
    { term: "timingbelt", definition: "A belt that synchronizes the engine's camshaft and crankshaft", points: 1 },
    { term: "coolant", definition: "A fluid that circulates through an engine to prevent overheating", points: 1 },
    { term: "antifreeze", definition: "A substance added to coolant to prevent freezing", points: 1 },
    { term: "lubricant", definition: "Oil that reduces friction between moving parts", points: 1 },
    { term: "fender", definition: "The part of a car that frames a wheel well", points: 1 },
    { term: "bumper", definition: "A bar at the front and back of a vehicle to absorb impact", points: 1 },
    { term: "grille", definition: "A grating that allows air to flow into the engine compartment", points: 1 },
    { term: "hood", definition: "The hinged cover over a vehicle's engine", points: 1 },
    { term: "trunk", definition: "The storage compartment at the rear of a car", points: 1 },
    { term: "sparetire", definition: "An extra tire carried in a vehicle for emergencies", points: 1 },
    { term: "jack", definition: "A tool used to lift a vehicle for tire changes", points: 1 },
    { term: "wrench", definition: "A tool used to tighten or loosen nuts and bolts", points: 1 },

    // === AVIATION TERMS ===
    { term: "fuselage", definition: "The main body section of an aircraft that holds crew and passengers", points: 1 },
    { term: "aileron", definition: "A hinged surface on an airplane wing used to control rolling", points: 1 },
    { term: "altimeter", definition: "An instrument used to measure the altitude of an object above sea level", points: 1 },
    { term: "cockpit", definition: "The compartment where the pilot and crew control the aircraft", points: 1 },
    { term: "hangar", definition: "A large building for housing and maintaining aircraft", points: 1 },
    { term: "biplane", definition: "An early type of aircraft with two main supporting surfaces", points: 1 },
    { term: "glider", definition: "A light aircraft that is designed to fly without using an engine", points: 1 },
    { term: "seaplane", definition: "An aircraft designed to take off from and land on water", points: 1 },
    { term: "airship", definition: "A power-driven aircraft that is kept buoyant by a body of gas", points: 1 },
    { term: "autopilot", definition: "A system used to control the path of an aircraft without human help", points: 1 },
    { term: "propeller", definition: "A device with blades that rotates to propel an aircraft", points: 1 },
    { term: "landinggear", definition: "The structure that supports an aircraft when it is on the ground", points: 1 },
    { term: "rudder", definition: "A vertical control surface used to steer an aircraft", points: 1 },
    { term: "elevator", definition: "A control surface that controls the pitch of an aircraft", points: 1 },
    { term: "flaps", definition: "Hinged surfaces on wings that increase lift during takeoff", points: 1 },
    { term: "spoilers", definition: "Devices that disrupt airflow to reduce lift", points: 1 },
    { term: "turbine", definition: "A rotary engine that extracts energy from fluid flow", points: 1 },
    { term: "avionics", definition: "Electronic systems used on aircraft", points: 1 },
    { term: "radar", definition: "A system for detecting objects using radio waves", points: 1 },
    { term: "transponder", definition: "A device that transmits a signal in response to a received signal", points: 1 },

    // === MARITIME TERMS ===
    { term: "anchor", definition: "A heavy object used to moor a vessel to the bottom", points: 1 },
    { term: "ferry", definition: "A boat or ship for conveying passengers across water", points: 1 },
    { term: "hull", definition: "The main body of a ship or other vessel", points: 1 },
    { term: "submarine", definition: "A watercraft capable of independent operation underwater", points: 1 },
    { term: "yacht", definition: "A medium-sized sailboat or motorboat for private cruising", points: 1 },
    { term: "kayak", definition: "A small, narrow watercraft propelled by a double-bladed paddle", points: 1 },
    { term: "canoe", definition: "A light narrow boat propelled by paddles", points: 1 },
    { term: "dinghy", definition: "A small inflatable boat used as a tender", points: 1 },
    { term: "catamaran", definition: "A yacht or other boat with twin hulls in parallel", points: 1 },
    { term: "trawler", definition: "A commercial fishing vessel designed to operate fishing trawls", points: 1 },
    { term: "tugboat", definition: "A powerful boat used for towing or pushing other vessels", points: 1 },
    { term: "bulkhead", definition: "An upright wall within the hull of a ship", points: 1 },
    { term: "periscope", definition: "An instrument used in submarines to see above water", points: 1 },
    { term: "lighthouse", definition: "A tower with a bright light to guide ships", points: 1 },
    { term: "marina", definition: "A specially designed harbor with moorings for yachts", points: 1 },
    { term: "dock", definition: "A structure where ships are loaded and unloaded", points: 1 },
    { term: "pier", definition: "A platform extending from shore over water", points: 1 },
    { term: "jetty", definition: "A structure projecting into water to protect a harbor", points: 1 },
    { term: "buoy", definition: "A floating object used as a navigation marker", points: 1 },
    { term: "rudder", definition: "A flat piece hinged vertically for steering a ship", points: 1 },
    { term: "keel", definition: "The structural backbone of a ship running along the bottom", points: 1 },
    { term: "mast", definition: "A tall upright post on a ship that supports sails", points: 1 },
    { term: "sail", definition: "A piece of fabric attached to a mast to catch wind", points: 1 },
    { term: "anchor", definition: "A heavy object used to moor a vessel to the bottom", points: 1 },
    { term: "compass", definition: "An instrument showing direction relative to magnetic north", points: 1 },

    // === RAILWAY TERMS ===
    { term: "locomotive", definition: "A powered railway vehicle used for pulling trains", points: 1 },
    { term: "monorail", definition: "A railroad in which the track consists of a single rail", points: 1 },
    { term: "tramway", definition: "A rail-based system usually running on city streets", points: 1 },
    { term: "maglev", definition: "A system of train transportation that uses magnetic levitation", points: 1 },
    { term: "caboose", definition: "A crew car at the end of a freight train", points: 1 },
    { term: "viaduct", definition: "A long bridge-like structure carrying a road or railway", points: 1 },
    { term: "railcar", definition: "A self-propelled railway vehicle designed to carry passengers", points: 1 },
    { term: "trolley", definition: "An electric streetcar that draws power from overhead wires", points: 1 },
    { term: "subway", definition: "An underground railway system", points: 1 },
    { term: "metro", definition: "A rapid transit system serving a metropolitan area", points: 1 },
    { term: "carriage", definition: "A railway vehicle for carrying passengers", points: 1 },
    { term: "wagon", definition: "A railway vehicle for carrying freight", points: 1 },
    { term: "coupler", definition: "A device for connecting railway cars together", points: 1 },
    { term: "railroad", definition: "A track made of steel rails for trains", points: 1 },
    { term: "depot", definition: "A railway station or bus station", points: 1 },
    { term: "platform", definition: "A raised area where passengers board trains", points: 1 },
    { term: "turnout", definition: "A mechanism that enables trains to switch tracks", points: 1 },
    { term: "signal", definition: "A device that gives instructions to train operators", points: 1 },
    { term: "gauge", definition: "The distance between the rails of a railway track", points: 1 },
    { term: "ballast", definition: "The stones or gravel forming the trackbed", points: 1 },
    { term: "sleeper", definition: "The horizontal supports for railway tracks", points: 1 },

    // === CYCLING TERMS ===
    { term: "bicycle", definition: "A vehicle with two wheels propelled by pedals", points: 1 },
    { term: "tricycle", definition: "A three-wheeled vehicle propelled by pedals", points: 1 },
    { term: "unicycle", definition: "A single-wheeled vehicle propelled by pedals", points: 1 },
    { term: "handlebar", definition: "The steering mechanism of a bicycle", points: 1 },
    { term: "saddle", definition: "The seat of a bicycle", points: 1 },
    { term: "pedal", definition: "A foot-operated lever that propels a bicycle", points: 1 },
    { term: "chain", definition: "A series of links that transmits power to the wheels", points: 1 },
    { term: "spoke", definition: "One of the rods connecting the wheel hub to the rim", points: 1 },
    { term: "rim", definition: "The outer edge of a wheel that holds the tire", points: 1 },
    { term: "derailleur", definition: "A mechanism for changing gears on a bicycle", points: 1 },
    { term: "helmet", definition: "Protective headgear worn by cyclists", points: 1 },
    { term: "pannier", definition: "A bag or basket attached to a bicycle", points: 1 },

    // === MOTORCYCLE TERMS ===
    { term: "motorcycle", definition: "A two-wheeled motor vehicle", points: 1 },
    { term: "scooter", definition: "A light motorcycle with a step-through frame", points: 1 },
    { term: "moped", definition: "A low-powered motorcycle with pedals", points: 1 },
    { term: "cruiser", definition: "A motorcycle designed for comfortable riding", points: 1 },
    { term: "chopper", definition: "A custom motorcycle with extended front forks", points: 1 },
    { term: "fairing", definition: "A protective shell on a motorcycle", points: 1 },
    { term: "kickstand", definition: "A prop that supports a motorcycle when parked", points: 1 },
    { term: "sidecar", definition: "An attached compartment for passengers", points: 1 },
    { term: "handlebar", definition: "The steering mechanism of a motorcycle", points: 1 },
    { term: "footpeg", definition: "A peg for the rider's feet on a motorcycle", points: 1 },

    // === INFRASTRUCTURE TERMS ===
    { term: "highway", definition: "A major road designed for high-speed traffic", points: 1 },
    { term: "freeway", definition: "A controlled-access highway with no tolls", points: 1 },
    { term: "expressway", definition: "A divided highway with limited access", points: 1 },
    { term: "intersection", definition: "A point where two or more roads meet", points: 1 },
    { term: "roundabout", definition: "A circular intersection for traffic flow", points: 1 },
    { term: "overpass", definition: "A bridge that carries one road over another", points: 1 },
    { term: "underpass", definition: "A tunnel that carries one road under another", points: 1 },
    { term: "tunnel", definition: "An underground passage for roads or railways", points: 1 },
    { term: "bridge", definition: "A structure spanning a physical obstacle", points: 1 },
    { term: "culvert", definition: "A structure allowing water to pass under a road", points: 1 },
    { term: "sidewalk", definition: "A paved path for pedestrians beside a road", points: 1 },
    { term: "crosswalk", definition: "A designated area for pedestrians to cross", points: 1 },
    { term: "median", definition: "A barrier separating opposing traffic lanes", points: 1 },
    { term: "shoulder", definition: "An emergency stopping area beside a road", points: 1 },
    { term: "ramp", definition: "A sloped connection between roads", points: 1 },
    { term: "tollbooth", definition: "A facility for collecting road usage fees", points: 1 },

    // === TWO WORD TERMS (2 points each) - 150+ phrases ===
    { term: "bus stop", definition: "A designated place where buses stop for passengers", points: 2 },
    { term: "cable car", definition: "A transport system where cars are pulled by a moving cable", points: 2 },
    { term: "public transport", definition: "Buses, trains, and other transport available to the public", points: 2 },
    { term: "bullet train", definition: "A high-speed passenger train", points: 2 },
    { term: "cargo ship", definition: "A vessel designed to carry goods across oceans", points: 2 },
    { term: "electric vehicle", definition: "A car that uses electric motors for propulsion", points: 2 },
    { term: "emergency brake", definition: "A secondary braking system for parking", points: 2 },
    { term: "fighter jet", definition: "A military aircraft designed for air combat", points: 2 },
    { term: "fire engine", definition: "A vehicle equipped for firefighting", points: 2 },
    { term: "forklift truck", definition: "An industrial vehicle for lifting heavy materials", points: 2 },
    { term: "garbage truck", definition: "A vehicle for collecting municipal waste", points: 2 },
    { term: "gas pedal", definition: "The foot-operated lever controlling engine speed", points: 2 },
    { term: "license plate", definition: "A metal plate displaying vehicle registration", points: 2 },
    { term: "main road", definition: "A major highway designed for high-volume traffic", points: 2 },
    { term: "monster truck", definition: "A vehicle with oversized tires for stunts", points: 2 },
    { term: "mountain bike", definition: "A bicycle designed for off-road cycling", points: 2 },
    { term: "parking lot", definition: "An area designated for leaving vehicles", points: 2 },
    { term: "rescue boat", definition: "A watercraft used to save people in distress", points: 2 },
    { term: "road rage", definition: "Aggressive behavior by a driver", points: 2 },
    { term: "safety belt", definition: "A strap securing occupants in a seat", points: 2 },
    { term: "school bus", definition: "A bus used to transport students", points: 2 },
    { term: "sea level", definition: "The base level for measuring elevation", points: 2 },
    { term: "speed limit", definition: "The maximum legal speed on a road", points: 2 },
    { term: "steering wheel", definition: "The circular control directing a vehicle", points: 2 },
    { term: "street car", definition: "A vehicle running on rails along streets", points: 2 },
    { term: "tow truck", definition: "A vehicle for moving disabled cars", points: 2 },
    { term: "zero emission", definition: "A vehicle that releases no pollutants", points: 2 },
    { term: "coast guard", definition: "A maritime search and rescue organization", points: 2 },
    { term: "heavy duty", definition: "Equipment designed for harsh work", points: 2 },
    { term: "cruise control", definition: "A system maintaining steady speed", points: 2 },
    { term: "landing gear", definition: "The structure supporting an aircraft on ground", points: 2 },
    { term: "merchant marine", definition: "Commercial ships carrying goods", points: 2 },
    { term: "night train", definition: "A railway service that travels overnight", points: 2 },
    { term: "oil tanker", definition: "A ship designed for bulk oil transport", points: 2 },
    { term: "outboard motor", definition: "A propulsion system for boats", points: 2 },
    { term: "paddle steamer", definition: "A steam-powered ship with a paddle wheel", points: 2 },
    { term: "passenger car", definition: "A vehicle designed to transport people", points: 2 },
    { term: "power steering", definition: "A system helping drivers turn wheels", points: 2 },
    { term: "radial tire", definition: "A tire design with cord arrangement", points: 2 },
    { term: "rearview mirror", definition: "A mirror showing what is behind", points: 2 },
    { term: "rumble strip", definition: "Raised patterns alerting drifting drivers", points: 2 },
    { term: "station wagon", definition: "A car with a long roof and cargo area", points: 2 },
    { term: "traffic jam", definition: "Crowded vehicles moving slowly", points: 2 },
    { term: "light aircraft", definition: "A small airplane with low takeoff weight", points: 2 },
    { term: "freight train", definition: "Railway cars used to transport cargo", points: 2 },
    { term: "double decker", definition: "A bus or train with two levels", points: 2 },
    { term: "hybrid car", definition: "A vehicle using both fuel and electric power", points: 2 },
    { term: "bicycle lane", definition: "A roadway portion for cyclists", points: 2 },
    { term: "parking meter", definition: "A device collecting parking fees", points: 2 },
    { term: "one-way street", definition: "A road where traffic flows in one direction", points: 2 },
    { term: "service station", definition: "A place for fuel and repairs", points: 2 },
    { term: "aircraft carrier", definition: "A warship serving as an airbase", points: 2 },
    { term: "check-in counter", definition: "Where travelers report at airports", points: 2 },
    { term: "drive shaft", definition: "A component transmitting torque", points: 2 },
    { term: "fuel injector", definition: "A nozzle spraying fuel into cylinders", points: 2 },
    { term: "spark plug", definition: "A device delivering electric current", points: 2 },
    { term: "brake pad", definition: "The component pressing on brake rotors", points: 2 },
    { term: "turn signal", definition: "A flashing light showing turning intention", points: 2 },
    { term: "catalytic converter", definition: "A device reducing toxic exhaust gases", points: 2 },
    { term: "jet engine", definition: "An engine producing thrust by ejecting gas", points: 2 },
    { term: "seaplane", definition: "An aircraft taking off and landing on water", points: 2 },
    { term: "stealth bomber", definition: "An aircraft difficult to detect by radar", points: 2 },
    { term: "supersonic", definition: "Speed greater than the speed of sound", points: 2 },
    { term: "afterburner", definition: "A component increasing jet engine thrust", points: 2 },
    { term: "autopilot", definition: "A system controlling aircraft without human help", points: 2 },
    { term: "bulkhead", definition: "An upright wall within a ship or aircraft", points: 2 },
    { term: "catamaran", definition: "A boat with twin hulls in parallel", points: 2 },
    { term: "drydock", definition: "A basin that can be flooded for ship repairs", points: 2 },
    { term: "galleon", definition: "A large sailing ship with multiple masts", points: 2 },
    { term: "kayak", definition: "A small watercraft with double-bladed paddle", points: 2 },
    { term: "lighthouse", definition: "A tower with a bright light guiding ships", points: 2 },
    { term: "marina", definition: "A harbor with moorings for pleasure boats", points: 2 },
    { term: "periscope", definition: "An instrument for seeing above water from submarines", points: 2 },
    { term: "trawler", definition: "A commercial fishing vessel", points: 2 },
    { term: "yacht", definition: "A medium-sized sailboat for cruising", points: 2 },
    { term: "caboose", definition: "A crew car at the end of a freight train", points: 2 },
    { term: "viaduct", definition: "A long bridge carrying a road or railway", points: 2 },

    // === THREE+ WORD TERMS (3 points each) - 100+ phrases ===
    { term: "air traffic control", definition: "Ground-based controllers directing aircraft safely", points: 3 },
    { term: "hot air balloon", definition: "A large bag of heated air carrying passengers", points: 3 },
    { term: "four-wheel drive", definition: "A system where the engine powers all four wheels", points: 3 },
    { term: "underground railway", definition: "A metro system operating below the surface", points: 3 },
    { term: "port of call", definition: "An intermediate stop for a ship", points: 3 },
    { term: "front-wheel drive", definition: "A system where the engine powers front wheels only", points: 3 },
    { term: "roll-on roll-off", definition: "Ships carrying wheeled cargo driven on and off", points: 3 },
    { term: "vertical take-off landing", definition: "Aircraft that can take off vertically without a runway", points: 3 },
    { term: "magnetic levitation train", definition: "A train using magnetic forces to float above tracks", points: 3 },
    { term: "internal combustion engine", definition: "An engine where fuel combustion occurs in cylinders", points: 3 },
    { term: "all-wheel drive", definition: "A system powering all wheels at all times", points: 3 },
    { term: "adaptive cruise control", definition: "A system automatically adjusting speed to maintain distance", points: 3 },
    { term: "blind spot monitoring", definition: "A system alerting drivers to vehicles in blind spots", points: 3 },
    { term: "lane departure warning", definition: "A system alerting when drifting from lanes", points: 3 },
    { term: "automatic emergency braking", definition: "A system applying brakes to prevent collisions", points: 3 },
    { term: "electronic stability control", definition: "A system preventing skidding", points: 3 },
    { term: "tire pressure monitoring", definition: "A system alerting to low tire pressure", points: 3 },
    { term: "keyless entry system", definition: "A system allowing vehicle access without keys", points: 3 },
    { term: "remote keyless ignition", definition: "A system starting vehicles with a button", points: 3 },
    { term: "global positioning system", definition: "A satellite-based navigation system", points: 3 },
    { term: "rear cross traffic alert", definition: "A system warning of traffic when reversing", points: 3 },
    { term: "parking assist system", definition: "A system helping drivers park", points: 3 },
    { term: "surround view camera", definition: "A system providing a 360-degree vehicle view", points: 3 },
    { term: "head-up display", definition: "A system projecting information on the windshield", points: 3 },
    { term: "regenerative braking system", definition: "A system recovering energy during braking", points: 3 },
    { term: "plug-in hybrid vehicle", definition: "A vehicle with both electric and fuel power that plugs in", points: 3 },
    { term: "battery electric vehicle", definition: "A vehicle powered entirely by batteries", points: 3 },
    { term: "fuel cell vehicle", definition: "A vehicle using hydrogen to generate electricity", points: 3 },
    { term: "autonomous driving system", definition: "A system enabling self-driving capabilities", points: 3 },
    { term: "vehicle to grid technology", definition: "Technology allowing vehicles to supply power to grids", points: 3 },
    { term: "high occupancy vehicle lane", definition: "A lane reserved for vehicles with multiple passengers", points: 3 },
    { term: "variable speed limit sign", definition: "Electronic signs displaying changing speed limits", points: 3 },
    { term: "intelligent transportation system", definition: "Advanced technology improving transport efficiency", points: 3 },
    { term: "traffic management center", definition: "A facility monitoring and controlling traffic", points: 3 },
    { term: "public key infrastructure", definition: "A system securing vehicle communications", points: 3 },
    { term: "vehicle to everything communication", definition: "Technology allowing vehicles to communicate with everything", points: 3 },
    { term: "advanced driver assistance system", definition: "Electronic systems assisting drivers", points: 3 },
    { term: "forward collision warning", definition: "A system alerting to potential front collisions", points: 3 },
    { term: "autonomous emergency steering", definition: "A system steering to avoid collisions", points: 3 },
    { term: "traffic sign recognition", definition: "A system identifying and displaying traffic signs", points: 3 },
    { term: "night vision assistant", definition: "A system improving visibility in darkness", points: 3 },
    { term: "driver monitoring system", definition: "A system detecting driver fatigue", points: 3 },
    { term: "vehicle dynamics control", definition: "A system managing vehicle stability", points: 3 },
    { term: "torque vectoring system", definition: "A system distributing torque to wheels", points: 3 },
    { term: "launch control system", definition: "A system optimizing acceleration from standstill", points: 3 },
    { term: "active suspension system", definition: "A system actively controlling vehicle suspension", points: 3 },
    { term: "variable geometry turbocharger", definition: "A turbocharger with adjustable vanes", points: 3 },
    { term: "direct fuel injection", definition: "A system injecting fuel directly into cylinders", points: 3 },
    { term: "continuously variable transmission", definition: "A transmission with infinite gear ratios", points: 3 },
    { term: "dual clutch transmission", definition: "A transmission using two clutches", points: 3 },
    { term: "all terrain vehicle", definition: "A vehicle designed for off-road use", points: 3 },
    { term: "recreational vehicle", definition: "A motor vehicle equipped for camping", points: 3 },
    { term: "sports utility vehicle", definition: "A vehicle combining SUV and car features", points: 3 },
    { term: "crossover utility vehicle", definition: "A vehicle combining car and SUV characteristics", points: 3 },
    { term: "light commercial vehicle", definition: "A vehicle for light cargo transport", points: 3 },
    { term: "heavy goods vehicle", definition: "A large vehicle for transporting goods", points: 3 },
    { term: "passenger service vehicle", definition: "A vehicle carrying passengers for hire", points: 3 },
    { term: "demand responsive transport", definition: "Flexible transport adapting to passenger needs", points: 3 },
    { term: "bus rapid transit", definition: "A high-quality bus-based transit system", points: 3 },
    { term: "light rail transit", definition: "A railway system using lighter vehicles", points: 3 },
    { term: "mass rapid transit", definition: "A high-capacity public transport system", points: 3 },
    { term: "personal rapid transit", definition: "A system of small automated vehicles", points: 3 },
    { term: "guided busway system", definition: "A bus system with physical guidance", points: 3 },
    { term: "trackless tram system", definition: "A tram-like system using rubber tires", points: 3 },
    { term: "aerial tramway system", definition: "A transport system using suspended cables", points: 3 },
    { term: "funicular railway system", definition: "A railway using cables on steep slopes", points: 3 },
    { term: "rack railway system", definition: "A railway using a toothed rack for steep grades", points: 3 },
    { term: "heritage railway", definition: "A preserved historic railway", points: 3 },
    { term: "scenic railway", definition: "A railway operating through scenic areas", points: 3 },
    { term: "mountain railway", definition: "A railway operating in mountainous terrain", points: 3 },
    { term: "intercity express", definition: "A high-speed train connecting cities", points: 3 },
    { term: "regional railway", definition: "A railway serving a specific region", points: 3 },
    { term: "commuter railway", definition: "A railway transporting commuters", points: 3 },
    { term: "suburban railway", definition: "A railway serving suburban areas", points: 3 },
    { term: "urban railway", definition: "A railway operating within cities", points: 3 },
    { term: "container ship", definition: "A vessel designed for containerized cargo", points: 2 },
    { term: "bulk carrier", definition: "A ship transporting bulk cargo", points: 2 },
    { term: "passenger ship", definition: "A vessel carrying passengers", points: 2 },
    { term: "cruise ship", definition: "A passenger ship for pleasure voyages", points: 2 },
    { term: "research vessel", definition: "A ship used for scientific research", points: 2 },
    { term: "icebreaker ship", definition: "A vessel designed to navigate ice-covered waters", points: 2 },
    { term: "dredging vessel", definition: "A ship for removing sediment", points: 2 },
    { term: "salvage tug", definition: "A vessel for rescuing distressed ships", points: 2 },
    { term: "supply vessel", definition: "A ship supporting offshore operations", points: 2 },
    { term: "patrol vessel", definition: "A ship for maritime law enforcement", points: 2 },
];